# Generated by Django 5.1.7 on 2025-03-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockMarketModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("trade_code", models.CharField(max_length=50)),
                ("high", models.CharField(max_length=50)),
                ("low", models.CharField(max_length=50)),
                ("open", models.CharField(max_length=50)),
                ("close", models.CharField(max_length=50)),
                ("volume", models.CharField(max_length=50)),
            ],
        ),
    ]
